version: "3.2"
services:

  redis:
    image: "redis:alpine"
    ports:
     - "6379:6379"

    volumes:
      - $PWD/data/redis:/var/lib/redis
  
  server:
    depends_on:
      - redis
    build:
      context: .
    ports:
     - "9000:9000"
    environment:
      REDIS_HOST: redis
      NOTIFY_LOG: matches.json
    volumes:
      - $PWD:/go/src/github.com/rezen/certmon
  
